//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Feedling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutFrmImage {
            get {
                object obj = ResourceManager.GetObject("AboutFrmImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected feeds?.
        /// </summary>
        internal static string FeedDeleteQuestion {
            get {
                return ResourceManager.GetString("FeedDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete feeds.
        /// </summary>
        internal static string FeedDeleteQuestionCaption {
            get {
                return ResourceManager.GetString("FeedDeleteQuestionCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon FeedlingIcon {
            get {
                object obj = ResourceManager.GetObject("FeedlingIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Config file.
        /// </summary>
        internal static string FeedwinManager_feedimportbtn_Click_Invalid_Config_file {
            get {
                return ResourceManager.GetString("FeedwinManager_feedimportbtn_Click_Invalid_Config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string FeedwinManager_FeedwinManager_About___ {
            get {
                return ResourceManager.GetString("FeedwinManager_FeedwinManager_About___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string FeedwinManager_FeedwinManager_Check_for_updates___ {
            get {
                return ResourceManager.GetString("FeedwinManager_FeedwinManager_Check_for_updates___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration....
        /// </summary>
        internal static string FeedwinManager_FeedwinManager_Configuration___ {
            get {
                return ResourceManager.GetString("FeedwinManager_FeedwinManager_Configuration___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Move Handles.
        /// </summary>
        internal static string FeedwinManager_FeedwinManager_Move_Mode {
            get {
                return ResourceManager.GetString("FeedwinManager_FeedwinManager_Move_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        internal static string FeedwinManager_FeedwinManager_Update_All {
            get {
                return ResourceManager.GetString("FeedwinManager_FeedwinManager_Update_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedling is now running over here. Come and add some feeds and other cool stuff..
        /// </summary>
        internal static string FirstTimeStartBalloonText {
            get {
                return ResourceManager.GetString("FirstTimeStartBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Config File.
        /// </summary>
        internal static string InvalidConfigError {
            get {
                return ResourceManager.GetString("InvalidConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string NoUpdatesAvailableCaption {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        internal static string NoUpdatesAvailableText {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are available!. Specicially, version {0}. {1}.
        /// </summary>
        internal static string UpdatesAvailableText {
            get {
                return ResourceManager.GetString("UpdatesAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error applying the update. Please try again later.
        ///
        ///Error was {0}.
        /// </summary>
        internal static string UpdatesErrorApplyText {
            get {
                return ResourceManager.GetString("UpdatesErrorApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking for updates. Please try again later.
        ///
        ///Error was {0}.
        /// </summary>
        internal static string UpdatesErrorCheckText {
            get {
                return ResourceManager.GetString("UpdatesErrorCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (compatible; Feedling/{0}; http://feedling.net).
        /// </summary>
        internal static string UserAgentString {
            get {
                return ResourceManager.GetString("UserAgentString", resourceCulture);
            }
        }
    }
}
